import type { Operation, Product } from '@/lib/types';

export const kpiData = {
  totalProducts: 1250,
  lowStockItems: 43,
  pendingReceipts: 8,
  pendingDeliveries: 12,
  internalTransfers: 5,
};

export const operations: Operation[] = [
  {
    id: 'op1',
    type: 'Receipt',
    reference: 'WH/IN/0001',
    partner: 'Global Supplies Inc.',
    scheduledDate: '2023-10-26',
    destination: 'Main Warehouse',
    product: 'Steel Rods',
    quantity: 500,
    status: 'Done',
  },
  {
    id: 'op2',
    type: 'Delivery',
    reference: 'WH/OUT/0001',
    partner: 'ConstructCo',
    scheduledDate: '2023-10-27',
    source: 'Main Warehouse',
    product: 'Cement Bags',
    quantity: 200,
    status: 'Ready',
  },
  {
    id: 'op3',
    type: 'Internal',
    reference: 'WH/INT/0001',
    scheduledDate: '2023-10-28',
    source: 'Main Warehouse',
    destination: 'Production Floor',
    product: 'Nuts and Bolts',
    quantity: 1000,
    status: 'Waiting',
  },
  {
    id: 'op4',
    type: 'Delivery',
    reference: 'WH/OUT/0002',
    partner: 'BuildIt All',
    scheduledDate: '2023-10-29',
    source: 'Warehouse B',
    product: 'Plywood Sheets',
    quantity: 150,
    status: 'Ready',
  },
  {
    id: 'op5',
    type: 'Adjustment',
    reference: 'WH/ADJ/0001',
    scheduledDate: '2023-10-25',
    destination: 'Main Warehouse',
    product: 'Safety Helmets',
    quantity: -5,
    status: 'Done',
  },
    {
    id: 'op6',
    type: 'Receipt',
    reference: 'WH/IN/0002',
    partner: 'Alpha Components',
    scheduledDate: '2023-10-30',
    destination: 'Warehouse C',
    product: 'Circuit Boards',
    quantity: 300,
    status: 'Draft',
  },
  {
    id: 'op7',
    type: 'Delivery',
    reference: 'WH/OUT/0003',
    partner: 'Innovate Tech',
    scheduledDate: '2023-10-31',
    source: 'Warehouse C',
    product: 'Circuit Boards',
    quantity: 50,
    status: 'Canceled',
  },
];

export const products: Product[] = [
    {
        id: 'prod_1',
        name: 'Steel Rods',
        sku: 'SR-001',
        category: 'Building Materials',
        uom: 'kg',
        stock: 500,
        location: 'Main Warehouse',
        imageUrl: 'https://picsum.photos/seed/prod1/400/400',
        imageHint: 'steel rods',
    },
    {
        id: 'prod_2',
        name: 'Cement Bags',
        sku: 'CB-001',
        category: 'Building Materials',
        uom: 'bag',
        stock: 180,
        location: 'Main Warehouse',
        imageUrl: 'https://picsum.photos/seed/prod2/400/400',
        imageHint: 'cement bags',
    },
    {
        id: 'prod_3',
        name: 'Nuts and Bolts',
        sku: 'NB-001',
        category: 'Fasteners',
        uom: 'box',
        stock: 1000,
        location: 'Production Floor',
        imageUrl: 'https://picsum.photos/seed/prod3/400/400',
        imageHint: 'nuts bolts',
    },
    {
        id: 'prod_4',
        name: 'Plywood Sheets',
        sku: 'PS-001',
        category: 'Wood Products',
        uom: 'sheet',
        stock: 150,
        location: 'Warehouse B',
        imageUrl: 'https://picsum.photos/seed/prod4/400/400',
        imageHint: 'plywood sheets',
    },
];
